# Generated by Django 4.2 on 2023-04-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0002_question_answers_amount_question_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
