# Generated by Django 4.1.7 on 2023-05-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0004_userslikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='static/img/ava.png', upload_to='avatars/%Y/%m/%d/'),
        ),
    ]
