# Generated by Django 4.1.7 on 2023-05-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/default/ava.png', upload_to='avatars/%Y/%m/%d/'),
        ),
    ]
